### ISSUE TITLE
Bug Fix Release for "fix(primitives): git rename b64Binary"

### ISSUE THREAD

**Issue by joepaquette** [tangdrew/fhir-ts#10]
It would be very helpful if a bug fix release of the three fhir-ts packages incorporating the "fix(primitives): git rename b64Binary" (commit 460f8325d76b91a1b67129f5aa915be23812f5dc)

**Comment by tangdrew** [comment]
Sorry bout that, version [0.4.2](https://www.npmjs.com/package/@tangdrew/primitives) should have that bug fix.

**Comment by joepaquette** [comment]
Thank you!
