### ISSUE TITLE
Problem with "@tangdrew/fhir-types": "^0.3.3" 

### ISSUE THREAD

**Issue by Mikhail42** [tangdrew/fhir-ts#11]
It's related with [7 issue](https://github.com/tangdrew/fhir-ts/issues/7)
Can't build project because  "Cannot find module './base64Binary'."

**Comment by tangdrew** [comment]
Can you provide more information? The issue you are referencing should've hopefully been resolved with this [release](https://github.com/tangdrew/fhir-ts/blob/master/packages/primitives/CHANGELOG.md#042-2019-03-08). Have you pulled down those changes?

**Comment by Mikhail42** [comment]
There is problem only with `npm` package, not with git. And it's solved by renaming `base64binary.*` to `base64Binary` in `node_modules/...`. Sorry for my English.

![fhir-types](https://user-images.githubusercontent.com/12397699/57189143-5903e500-6f13-11e9-86dd-5531496062b8.png)

**Comment by tangdrew** [comment]
Good catch! I wasn't clearing out the build directory so there were some stale built files from before I renamed to `base64Binary.ts`. The [0.3.4 release](https://github.com/tangdrew/fhir-ts/blob/master/packages/fhir-types/CHANGELOG.md#034-2019-05-11) of `fhir-types` should have the fixed version.
