### ISSUE TITLE
fhir-ts outputs only 15 data-type exports, no resources

### ISSUE THREAD

**Issue by fallasd** [tangdrew/fhir-ts#3]
Hello, I have installed fhir-ts globally - npm install -g fhir-ts. No errors or exceptions appear. When I follow the instructions (README) to create a FHIR Questionnaire resource, only a small file with 15 lines is generated.

The command I used was fhir-ts "structure-definitions/Questionnaire.profile.json" "c:\temp\fhir-types"
I have also tried fhir-ts "structure-definitions/**.profile.json" "c:\temp\fhir-types"

The content of the generated file (fhir.d.ts) in both cases is:

export declare type integer = number;
export declare type decimal = number;
export declare type uri = string;
export declare type base64Binary = string;
export declare type instant = string;
export declare type date = string;
export declare type dateTime = string;
export declare type time = string;
export declare type code = string;
export declare type oid = string;
export declare type id = string;
export declare type markdown = string;
export declare type unsignedInt = number;
export declare type positiveInt = number;
export declare type xhtml = string;

What am I doing wrong?

**Comment by tangdrew** [comment]
This project is still under development and isn't "production ready", sorry I should make that more clear. It currently won't generate all of the nested types when you pass a single structure definition, just the types defined in that structure definition. Are you providing the path to a directory with FHIR structure definitions in it? If it can't find any files that match the glob pattern (e.g.`structure-definitions/**.profile.json`) then it won't throw any errors and just generate type declarations for the FHIR primitive types which matches the behavior you've described. You can download the base FHIR structure definitions by cloning down this project or at https://www.hl7.org/fhir/downloads.html.

**Comment by tangdrew** [comment]
@fallasd Also, if you are just looking for types generated from the base specification structure definitions, rather than profiled structure definitions, those are shipped with this project [here](https://github.com/tangdrew/fhir-ts/blob/master/types/fhir.d.ts).

**Comment by fallasd** [comment]
@tangdrew Thanks for the updates. I have cloned the project and see that the /types sub-directory contains the complete typescript suite of FHIR resources. This should suffice for the experiment we are conducting at the moment (an Angular 6 project).

I will be interested to see how your project progresses.
