### ISSUE TITLE
Feature Request: Export the `structure-definitions` folder along with the generated interfaces

### ISSUE THREAD

**Issue by joepaquette** [tangdrew/fhir-ts#9]
Export the `structure-definitions\R4` folder along with the generated interfaces in the `src`R4` folder in a parallel folder. FHIR conformant servers must provide a capability statement that includes the supported profile definitions. Exporting the `*.profile.canconical.json` files from which the interfaces are generated would greatly facilitate the task to generate the required capability statement.

**Comment by tangdrew** [comment]
I'm not sure I understand how exporting the base FHIR StructureDefinitions I'm using to generate the [fhir-types](https://github.com/tangdrew/fhir-ts/tree/master/packages/fhir-types) helps with building a CapabilityStatement for a FHIR server? The CapabilityStatement should describe a specific FHIR implementation.

**Comment by joepaquette** [comment]
I mis-read the FHIR spec for the CapabilityStatement. I was thinking that the StructureDefinition was embedded but the spec indicates that it only uses the URI for the StructureDefinition.
